### ISSUE TITLE
[1.18.2] Flashing black screen on the horizon

### ISSUE THREAD

**Issue by 3Monika4** [CreativeMD/EnhancedVisuals#122] opened 2023-08-16 10:27 UTC
On the white part of the skybox, every time the heartbeat effect occurs it flashes black. Heres a screencap i was able to get of the frames where it does that
![image](https://github.com/CreativeMD/EnhancedVisuals/assets/60331524/98731116-71ef-4c71-ad1c-387614cf24fd)
I don't really know how to fix this

**Comment by CreativeMD** [comment] 2023-08-23 17:56
Any other mods installed? Maybe it's a conflict with another mod? In theory I do not support 1.18.2 anymore. Would be interesting to know if this still happens in 1.20.

**Comment by CreativeMD** [comment] 2023-10-25 12:28
I will close this issue for now. Could not reproduce it. If it is still there in 1.20, post a list of mods and I will reopen the issue.

**Closed as completed by CreativeMD** 2023-10-25 12:28 UTC
