### ISSUE TITLE
Leak

### ISSUE THREAD

**Issue by axalox** [CreativeMD/EnhancedVisuals#69] opened 2021-02-26 17:21 UTC
Hello

Good mod thx for it ;)

I've looked server logs and i see this :

```
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
WARNING: 2 leak records were discarded because the leak record count is limited to 4. Use system property io.netty.leakDetection.maxRecords to increase the limit.
Recent access records: 5
#5:
io.netty.buffer.AdvancedLeakAwareByteBuf.writeInt(AdvancedLeakAwareByteBuf.java:558)
team.creative.enhancedvisuals.common.packet.DamagePacket.writeBytes(DamagePacket.java:67)
com.creativemd.creativecore.common.packet.CreativeMessageHandler.toBytes(CreativeMessageHandler.java:61)
net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30)
net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26)
net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81)
io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
```
EnhancedVisuals_v1.3.24_mc1.12.2.jar
Minecraft server 1.12.2
Forge 1.12.2 - 14.23.5.2854

**Comment by CreativeMD** [comment] 2021-04-08 16:05
Will be fixed in the upcoming CreativeCore release. Probably will be there in a week or so.

**Comment by CreativeMD** [comment] 2021-04-08 16:06
Also I will close this here as this is a duplicate of: https://github.com/CreativeMD/CreativeCore/issues/109

**Closed as completed by CreativeMD** 2021-04-08 16:06 UTC
