### ISSUE TITLE
These blood can eventually make you blind.

### ISSUE THREAD

**Issue by vrgtics** [CreativeMD/EnhancedVisuals#89] opened 2022-05-05 16:04 UTC
I don't know is it necessary to actually make it affect any Gui interface, **_yes it's happened Any Gui not only there_**. 
lol, how do I watch?

![20220505-235559](https://user-images.githubusercontent.com/99676066/166964026-be7d3ab9-26b0-43e1-b957-efb8dbfe91fc.png)

- _I have a suggestion of making these blood effect to liitle transparency_

also can make me drop fps, but that's alright.

**Comment by FreezePhoenix** [comment] 2022-05-12 11:56
They should fade over time.

**Comment by vrgtics** [comment] 2022-05-12 13:57
> They should fade over time.

you have no idea what's the problem when you actually using. 
I can give you More above my picture, I'm on the Mod Menu list, which mean I'm Pausing the Game, which mean this mod is designed in-game processing, which mean fading doesn't operate while game pauses, well that sucks. 🤦‍♀️🤦‍♀️🤦‍♀️

**Comment by FreezePhoenix** [comment] 2022-05-13 12:11
Confirmed - the overlay does not tick when you are not in-game. This will persist even to the main menu. Happens with all overlays, including location-based ones, such as the "slender" overlay.

**Comment by CreativeMD** [comment] 2022-06-13 10:09
The issue is that `END_CLIENT_TICK` does not tick in the menu. The `RenderTickEvent` in Forge however does. This means effects will dissolve on forge but not on fabric. I got no idea how to fix this. Is there an event in fabric which also ticks in the main menu?

**Comment by FreezePhoenix** [comment] 2022-06-13 16:05
Where *precisely* does `RenderTickEvent` trigger?

**Comment by CreativeMD** [comment] 2022-06-13 16:51
In `Minecraft.runTick(boolean)`:

```java
...
if (!this.noRender) {
         net.minecraftforge.event.ForgeEventFactory.onRenderTickStart(this.pause ? this.pausePartialTick : this.timer.partialTick);
         this.profiler.popPush("gameRenderer");
         this.gameRenderer.render(this.pause ? this.pausePartialTick : this.timer.partialTick, i, p_91384_);
         this.profiler.popPush("toasts");
         this.toast.render(new PoseStack());
         this.profiler.pop();
         net.minecraftforge.event.ForgeEventFactory.onRenderTickEnd(this.pause ? this.pausePartialTick : this.timer.partialTick);
}
...
```

**Comment by FreezePhoenix** [comment] 2022-06-13 21:09
Idea: Mixin to the GameRenderer

**Comment by CreativeMD** [comment] 2022-06-14 11:21
I tested the newest version in fabric minecraft 1.19 and it works in the same way as forge. I think this issue has been fixed in the meantime.

**Closed as completed by CreativeMD** 2022-06-14 11:21 UTC
