### ISSUE TITLE
Two bugs after entering nether (Heat/Cold overlay 100% opaque, etc)

### ISSUE THREAD

**Issue by bigmagicjerk** [CreativeMD/EnhancedVisuals#55] opened 2020-10-16 18:26 UTC
After about 15 hours in a world I entered the nether, and now when I adjust the player's camera to all angles except a few the heat/cold overlay is 100% opaque and completely obscures the screen. Blood splatters also seem to be coming through as huge white squares on the screen. 

This is without shaders and using the ROTN BPG modpack. Others do not seem to be experiencing this - any suggestions as to how to resolve this would be greatly appreciated.

Best,
BMJ

**Comment by CreativeMD** [comment] 2020-11-23 09:31
I can't reproduce this issue ... somebody else is having a similar issue. https://github.com/CreativeMD/EnhancedVisuals/issues/56 Maybe you are having the same?

**Comment by Shibva** [comment] 2020-11-23 13:54
This might be the same if WAILA is present

**Comment by CreativeMD** [comment] 2020-11-23 16:43
Fixed in the newest version.

**Closed as completed by CreativeMD** 2020-11-23 16:43 UTC

**Comment by Shibva** [comment] 2020-11-23 18:46
so you found it

I hope that this fix will be the fix that fixes

and if ti does, praize thy soul
